name: Deploy Backend to Google Cloud Run

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.FIREBASE_PROJECT_ID }}
          service_account_key: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          export_default_credentials: true

      - name: Authenticate Docker
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.FIREBASE_PROJECT_ID }}/backend -f infra/docker/backend/Dockerfile.prod ./apps/backend
          docker push gcr.io/${{ secrets.FIREBASE_PROJECT_ID }}/backend

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy atom-challenge-backend \
            --image gcr.io/${{ secrets.FIREBASE_PROJECT_ID }}/backend \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --port 3000
