name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Login to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

    - name: Configure gcloud CLI
      run: |
        gcloud config set project ${{ secrets.FIREBASE_PROJECT_ID }}
        gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.FIREBASE_PROJECT_ID }}/backend ./apps/backend
        docker push gcr.io/${{ secrets.FIREBASE_PROJECT_ID }}/backend

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy backend \
        --image gcr.io/${{ secrets.FIREBASE_PROJECT_ID }}/backend \
        --platform managed \
        --region us-central1 \
        --allow-unauthenticated
